export interface CityData {
  city_id: string;
  city_name: string;
  state: string;
  tier: 1 | 2 | 3;
  location: { lat: number; lng: number };
  risk_score: string;
  priorityLevel: 'High' | 'Medium' | 'Low';
  demographics: {
    population: number;
    density_sq_km: number;
    infrastructure_index: string;
    is_rural?: boolean;
    village_category?: 'A' | 'B' | 'C'; // Category based on connectivity/services
  };
  complaints_summary: {
    total_received: number;
    top_category: string;
    primary_languages: string[];
  };
  gemini_ai_recommendation: string;
  contech_estimates: {
    suggested_structure: string;
    estimated_concrete_m3: number;
    estimated_steel_tons: number;
    projected_cost_inr: string;
  };
  funding_scheme: string;
  recent_feed: Array<{
    id: string;
    type: "voice" | "image" | "text";
    user_location: string;
    transcript: string;
    category: string;
    timestamp: string;
    original_audio_lang?: string;
    regional_transcript?: string;
    audio_duration_sec?: number;
    urgency_level?: 'Low' | 'Medium' | 'High' | 'Critical';
  }>;
}

export interface GovernmentBuild {
  id: string;
  title: string;
  city: string;
  state: string;
  tier: 1 | 2 | 3;
  ward: string;
  location: { lat: number; lng: number };
  purpose: 'School' | 'Hospital' | 'Sports Ground / Stadium' | 'Public Garden & Park' | 'Drainage & Water Plant' | 'Transport Hub & Bridge' | 'Administrative Office';
  governingBody: 'Municipal Corporation (Local)' | 'State Government (PWD)' | 'Smart City SPV' | 'State Urban Development';
  status: 'Completed' | 'Under Construction' | 'Commissioned';
  totalCostINR: string;
  costCrores: number;
  timeline: string;
  completionYear: string;
  areaOccupied: string;
  description: string;
  citizenBeneficiaries: string;
  citizenRating: number; // 1 to 5
  satisfactionPercent: number;
  contractorAgency: string;
  aiMapPrompt?: string;
  sourceAttribution?: string;
}

export interface CivicProposal {
  id: string;
  title: string;
  proposedBy: 'Government Department' | 'Citizen Initiative';
  departmentOrAuthor: string;
  city: string;
  state: string;
  tier: 1 | 2 | 3;
  ward: string;
  locationCoords: { lat: number; lng: number };
  purpose: 'School' | 'Hospital' | 'Public Garden' | 'Sports Ground / Stadium' | 'Administrative Office' | 'Drainage / Flood Defense' | 'Community Hall' | 'Transport Hub & Bridge';
  costEstimateINR: string;
  costCrores: number;
  timelineEstimated: string;
  areaRequired: string;
  description: string;
  justification: string;
  status: 'Open for Voting' | 'Approved by Public' | 'Rejected by Public';
  votesApprove: number;
  votesReject: number;
  userVoted?: 'approve' | 'reject' | null;
  citizenFeedback: Array<{
    id: string;
    author: string;
    vote: 'approve' | 'reject';
    comment: string;
    time: string;
    upvotes: number;
  }>;
  environmentalImpact: 'Minimal' | 'Moderate' | 'Positive Eco-Buffer' | 'Requires Tree Relocation';
  createdDate: string;
  aiMapPrompt?: string;
  isFutureMegaProject?: boolean;
}

export interface AIMapPromptItem {
  id: string;
  title: string;
  category: 'Government & Public Infra' | 'Private & Corporate Landmark' | 'Mega Future Construction';
  locationName: string;
  coords: { lat: number; lng: number };
  budgetOrCost: string;
  areaOrSize: string;
  purpose: string;
  builtBy: string;
  exactPrompt: string;
  notes: string;
  status: 'Completed' | 'Under Construction' | 'Proposed / Voting';
  keyHighlight: string;
}

export const MOCK_CITIES: Record<string, CityData> = {
  // === TIER 1 CITIES ===
  Mumbai: {
    city_id: "IND-MH-01",
    city_name: "Mumbai",
    state: "Maharashtra",
    tier: 1,
    location: { lat: 19.0760, lng: 72.8777 },
    risk_score: "9.2 / 10 (Critical Hotspot)",
    priorityLevel: "High",
    demographics: {
      population: 12500000,
      density_sq_km: 21000,
      infrastructure_index: "68/100",
    },
    complaints_summary: {
      total_received: 4820,
      top_category: "Monsoon Flooding & Sea Outfall Drainage",
      primary_languages: ["Marathi", "Hindi", "English"],
    },
    gemini_ai_recommendation:
      "Severe waterlogging recorded across Kurla, Dadar, and Hindmata basins. Recommend high-capacity underground holding tanks & automated floodgate valves under Coastal Infrastructure Fund.",
    contech_estimates: {
      suggested_structure: "Subterranean Stormwater Holding Sump & Tidal Pumping Station",
      estimated_concrete_m3: 3200,
      estimated_steel_tons: 420,
      projected_cost_inr: "₹ 48.50 Crores",
    },
    funding_scheme: "State Coastal Resilience & MCGM Capital Fund",
    recent_feed: [
      {
        id: "mb-101",
        type: "voice",
        user_location: "Kurla West, LBS Marg",
        transcript: "Water knee-deep after only 45 minutes of rain. Natural nullah is choked with construction silt.",
        regional_transcript: "फक्त ४५ मिनिटांच्या पावसात गुडघ्यापर्यंत पाणी साचले आहे. बांधकामाच्या मातीमुळे नैसर्गिक नाला पूर्णपणे चोक झाला आहे.",
        original_audio_lang: "Marathi / Hindi (मराठी/हिंदी)",
        audio_duration_sec: 14,
        urgency_level: "Critical",
        category: "Drainage",
        timestamp: "8 mins ago",
      },
      {
        id: "mb-102",
        type: "image",
        user_location: "Dadar TT Circle",
        transcript: "Bus lane cave-in near flyover pillar base. Needs rapid road stabilization.",
        regional_transcript: "फ्लायओव्हर पिलरच्या पायाजवळ बस लेन खचली आहे. रस्ता तात्काळ स्थिर करण्याची गरज आहे.",
        original_audio_lang: "Marathi (मराठी)",
        audio_duration_sec: 10,
        urgency_level: "High",
        category: "Road & Transport",
        timestamp: "24 mins ago",
      },
    ],
  },
  Delhi: {
    city_id: "IND-DL-01",
    city_name: "Delhi",
    state: "Delhi NCR",
    tier: 1,
    location: { lat: 28.6139, lng: 77.2090 },
    risk_score: "9.4 / 10 (Severe Deficit)",
    priorityLevel: "High",
    demographics: {
      population: 16800000,
      density_sq_km: 11300,
      infrastructure_index: "64/100",
    },
    complaints_summary: {
      total_received: 5210,
      top_category: "Air Filtration Green Corridors & Dust Suppression",
      primary_languages: ["Hindi", "Punjabi", "English"],
    },
    gemini_ai_recommendation:
      "Heavy particulate matter concentration along industrial ring road. Recommend misting smart poles and vertical air-purifying urban forestry canopies.",
    contech_estimates: {
      suggested_structure: "Micro-Forestry Buffer & Smart Smog Filtration Columns",
      estimated_concrete_m3: 840,
      estimated_steel_tons: 95,
      projected_cost_inr: "₹ 14.20 Crores",
    },
    funding_scheme: "National Clean Air Programme (NCAP)",
    recent_feed: [
      {
        id: "dl-101",
        type: "text",
        user_location: "Anand Vihar ISBT",
        transcript: "Heavy dust plume from unshielded bypass work. No water sprinkling done.",
        category: "Air Quality",
        timestamp: "15 mins ago",
      },
    ],
  },
  Bengaluru: {
    city_id: "IND-KA-01",
    city_name: "Bengaluru",
    state: "Karnataka",
    tier: 1,
    location: { lat: 12.9716, lng: 77.5946 },
    risk_score: "8.7 / 10 (Critical Hotspot)",
    priorityLevel: "High",
    demographics: {
      population: 8440000,
      density_sq_km: 4400,
      infrastructure_index: "69/100",
    },
    complaints_summary: {
      total_received: 3950,
      top_category: "Lake Inflow Rejuvenation & Groundwater Depletion",
      primary_languages: ["Kannada", "English", "Telugu"],
    },
    gemini_ai_recommendation:
      "Bellandur & Varthur feeder canals clogged with industrial sludge. Urgent mandate for tertiary decentralized STP and bio-fencing.",
    contech_estimates: {
      suggested_structure: "Decentralized Eco-STP & Inflow Wetland Filter",
      estimated_concrete_m3: 1600,
      estimated_steel_tons: 140,
      projected_cost_inr: "₹ 26.80 Crores",
    },
    funding_scheme: "AMRUT 2.0 & Karnataka Urban Water Board",
    recent_feed: [
      {
        id: "blr-101",
        type: "voice",
        user_location: "Sarjapur Road Ward 150",
        transcript: "Borewells completely dry in our layout. Tanker mafia charging 2000 rupees.",
        category: "Water Supply",
        timestamp: "35 mins ago",
      },
    ],
  },
  Hyderabad: {
    city_id: "IND-TS-01",
    city_name: "Hyderabad",
    state: "Telangana",
    tier: 1,
    location: { lat: 17.3850, lng: 78.4867 },
    risk_score: "7.6 / 10 (High Priority)",
    priorityLevel: "Medium",
    demographics: {
      population: 6800000,
      density_sq_km: 18100,
      infrastructure_index: "74/100",
    },
    complaints_summary: {
      total_received: 2420,
      top_category: "Musi River Basin & Storm Drain Encroachment",
      primary_languages: ["Telugu", "Urdu", "English"],
    },
    gemini_ai_recommendation:
      "Old city storm channels require precast concrete retaining walls and flood diversion barriers before monsoon.",
    contech_estimates: {
      suggested_structure: "Precast Concrete Retaining Channel & Silt Traps",
      estimated_concrete_m3: 980,
      estimated_steel_tons: 85,
      projected_cost_inr: "₹ 11.50 Crores",
    },
    funding_scheme: "Strategic Nala Development Programme (SNDP)",
    recent_feed: [
      {
        id: "hyd-101",
        type: "image",
        user_location: "Charminar Zone, Ward 22",
        transcript: "Drainage wall collapsed after thunderstorm. Sewage leaking into residential alley.",
        category: "Drainage",
        timestamp: "50 mins ago",
      },
    ],
  },
  Chennai: {
    city_id: "IND-TN-01",
    city_name: "Chennai",
    state: "Tamil Nadu",
    tier: 1,
    location: { lat: 13.0827, lng: 80.2707 },
    risk_score: "8.3 / 10 (High Priority)",
    priorityLevel: "High",
    demographics: {
      population: 7080000,
      density_sq_km: 26500,
      infrastructure_index: "72/100",
    },
    complaints_summary: {
      total_received: 2890,
      top_category: "Velachery Basin Flood Gates & Desalination Distribution",
      primary_languages: ["Tamil", "English"],
    },
    gemini_ai_recommendation:
      "Low-lying areas vulnerable to inundation. Implement automated sluice gates connected to Buckingham Canal.",
    contech_estimates: {
      suggested_structure: "Hydraulic Sluice Gate System & Precast Box Drains",
      estimated_concrete_m3: 1450,
      estimated_steel_tons: 130,
      projected_cost_inr: "₹ 19.80 Crores",
    },
    funding_scheme: "World Bank Coastal Urban Climate Fund",
    recent_feed: [
      {
        id: "chn-101",
        type: "voice",
        user_location: "Velachery Ward 178",
        transcript: "Water stagnant for two days on main street. Pumping station is offline.",
        category: "Drainage",
        timestamp: "1 hour ago",
      },
    ],
  },
  Kolkata: {
    city_id: "IND-WB-01",
    city_name: "Kolkata",
    state: "West Bengal",
    tier: 1,
    location: { lat: 22.5726, lng: 88.3639 },
    risk_score: "8.1 / 10 (High Priority)",
    priorityLevel: "High",
    demographics: {
      population: 4490000,
      density_sq_km: 24300,
      infrastructure_index: "66/100",
    },
    complaints_summary: {
      total_received: 2650,
      top_category: "Heritage Drainage Lines & Electric Tram Grid Safety",
      primary_languages: ["Bengali", "Hindi", "English"],
    },
    gemini_ai_recommendation:
      "120-year-old brick sewer mains in Central Kolkata experiencing soil subsidence. Trenchless CIPP relining strongly advised.",
    contech_estimates: {
      suggested_structure: "Trenchless CIPP Structural Relining & Reinforced Manholes",
      estimated_concrete_m3: 520,
      estimated_steel_tons: 45,
      projected_cost_inr: "₹ 8.90 Crores",
    },
    funding_scheme: "KMC Urban Renewal Special Mission",
    recent_feed: [
      {
        id: "kol-101",
        type: "text",
        user_location: "Bowbazar, Ward 48",
        transcript: "Cracks appearing on road surface above the central drainage trunk line.",
        category: "Infrastructure",
        timestamp: "2 hours ago",
      },
    ],
  },

  // === TIER 2 CITIES ===
  Indore: {
    city_id: "IND-MP-01",
    city_name: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    location: { lat: 22.7196, lng: 75.8577 },
    risk_score: "8.9 / 10 (Critical Hotspot)",
    priorityLevel: "High",
    demographics: {
      population: 2420000,
      density_sq_km: 9700,
      infrastructure_index: "62/100",
    },
    complaints_summary: {
      total_received: 1420,
      top_category: "Drainage & Flood Management",
      primary_languages: ["Hindi", "Malvi", "English"],
    },
    gemini_ai_recommendation:
      "High concentration of citizen audio reports in Ward 12 regarding storm-water overflow. Recommend immediate allocation for a reinforced concrete culvert under AMRUT 2.0.",
    contech_estimates: {
      suggested_structure: "Box Culvert & Subsurface Drainage Line",
      estimated_concrete_m3: 450,
      estimated_steel_tons: 32,
      projected_cost_inr: "₹ 1.85 Crores",
    },
    funding_scheme: "AMRUT 2.0 (Urban Water & Sewage)",
    recent_feed: [
      {
        id: "feed-101",
        type: "voice",
        user_location: "Vijay Nagar, Sector 4",
        transcript: "Water pipeline burst near Sector 4 square. Sewage water entering main road.",
        regional_transcript: "सेक्टर 4 चौराहे के पास मुख्य पानी की पाइपलाइन फट गई है। गंदा पानी सड़क पर भर रहा है।",
        original_audio_lang: "Hindi / Malvi (हिंदी/मालवी)",
        audio_duration_sec: 12,
        urgency_level: "High",
        category: "Water Supply",
        timestamp: "10 mins ago",
      },
      {
        id: "feed-102",
        type: "image",
        user_location: "Bhawarkua Circle",
        transcript: "Deep potholes on arterial road causing major traffic bottleneck during peak hours.",
        regional_transcript: "मुख्य सड़क पर भवरकुआं चौराहे के पास गहरे गड्ढों के कारण पीक ऑवर्स में भारी जाम लग रहा है।",
        original_audio_lang: "Hindi (हिंदी)",
        audio_duration_sec: 10,
        urgency_level: "Medium",
        category: "Road & Transport",
        timestamp: "32 mins ago",
      },
    ],
  },
  Pune: {
    city_id: "IND-MH-02",
    city_name: "Pune",
    state: "Maharashtra",
    tier: 2,
    location: { lat: 18.5204, lng: 73.8567 },
    risk_score: "7.8 / 10 (High Priority)",
    priorityLevel: "Medium",
    demographics: {
      population: 3120000,
      density_sq_km: 9400,
      infrastructure_index: "73/100",
    },
    complaints_summary: {
      total_received: 1890,
      top_category: "Mula-Mutha Riverfront Silt & Footpath Obstructions",
      primary_languages: ["Marathi", "Hindi", "English"],
    },
    gemini_ai_recommendation:
      "Hinjawadi IT corridor and Baner link roads facing storm runoff choking. Recommend precast reinforced concrete side gutters.",
    contech_estimates: {
      suggested_structure: "Precast Concrete Drainage Flume & Percolation Trenches",
      estimated_concrete_m3: 620,
      estimated_steel_tons: 54,
      projected_cost_inr: "₹ 4.10 Crores",
    },
    funding_scheme: "Pune Smart City SPV & PMRDA Fund",
    recent_feed: [
      {
        id: "pune-101",
        type: "voice",
        user_location: "Baner Road, Ward 9",
        transcript: "Footpath dug up for cables 4 months ago and left open. Senior citizens cannot walk safely.",
        category: "Pedestrian Safety",
        timestamp: "22 mins ago",
      },
    ],
  },
  Jaipur: {
    city_id: "IND-RJ-01",
    city_name: "Jaipur",
    state: "Rajasthan",
    tier: 2,
    location: { lat: 26.9124, lng: 75.7873 },
    risk_score: "7.1 / 10 (Moderate Hotspot)",
    priorityLevel: "Medium",
    demographics: {
      population: 3040000,
      density_sq_km: 6400,
      infrastructure_index: "70/100",
    },
    complaints_summary: {
      total_received: 1350,
      top_category: "Dravyavati River Basin Siltation & Water Scarcity",
      primary_languages: ["Hindi", "Rajasthani", "English"],
    },
    gemini_ai_recommendation:
      "Water table dropping drastically in Sanganer sector. Deploy dual rainwater harvesting recharge wells in municipal buildings.",
    contech_estimates: {
      suggested_structure: "Subsurface Aquifer Recharge Shafts & Filter Chambers",
      estimated_concrete_m3: 310,
      estimated_steel_tons: 22,
      projected_cost_inr: "₹ 2.20 Crores",
    },
    funding_scheme: "Atal Bhujal Yojana & JDA Funds",
    recent_feed: [
      {
        id: "jpr-101",
        type: "text",
        user_location: "Mansarovar Sector 7",
        transcript: "Water supply pressure is extremely low, barely 10 minutes of trickle each morning.",
        category: "Water Supply",
        timestamp: "40 mins ago",
      },
    ],
  },
  Lucknow: {
    city_id: "IND-UP-01",
    city_name: "Lucknow",
    state: "Uttar Pradesh",
    tier: 2,
    location: { lat: 26.8467, lng: 80.9462 },
    risk_score: "7.5 / 10 (Moderate Hotspot)",
    priorityLevel: "Medium",
    demographics: {
      population: 2810000,
      density_sq_km: 7900,
      infrastructure_index: "67/100",
    },
    complaints_summary: {
      total_received: 1540,
      top_category: "Gomti Riverbank Canalization & Potholes",
      primary_languages: ["Hindi", "Urdu", "Awadhi"],
    },
    gemini_ai_recommendation:
      "Gomti overflow risks in low-lying Aliganj neighborhoods. Install reinforced embankment slope protection and pumping sumps.",
    contech_estimates: {
      suggested_structure: "RCC Retaining Wall & High-Discharge Pumping Sump",
      estimated_concrete_m3: 580,
      estimated_steel_tons: 48,
      projected_cost_inr: "₹ 3.75 Crores",
    },
    funding_scheme: "State Urban Development Agency (SUDA)",
    recent_feed: [
      {
        id: "lko-101",
        type: "image",
        user_location: "Hazratganj Outer Ring",
        transcript: "Road surface chipped off creating hazardous craters right near government hospital gate.",
        category: "Road & Transport",
        timestamp: "1 hour ago",
      },
    ],
  },
  Surat: {
    city_id: "IND-GJ-01",
    city_name: "Surat",
    state: "Gujarat",
    tier: 2,
    location: { lat: 21.1702, lng: 72.8311 },
    risk_score: "6.9 / 10 (Active Surveillance)",
    priorityLevel: "Low",
    demographics: {
      population: 4460000,
      density_sq_km: 13700,
      infrastructure_index: "81/100",
    },
    complaints_summary: {
      total_received: 1120,
      top_category: "Tapi River Flood Protection & Textile Waste Effluents",
      primary_languages: ["Gujarati", "Hindi", "English"],
    },
    gemini_ai_recommendation:
      "Solid waste accumulation in Pandesara industrial corridor. Implement automated robotic trash skimmers and monitored smart bins.",
    contech_estimates: {
      suggested_structure: "Automated Industrial Effluent Siphon & Monitoring Weir",
      estimated_concrete_m3: 410,
      estimated_steel_tons: 36,
      projected_cost_inr: "₹ 2.90 Crores",
    },
    funding_scheme: "Surat Municipal Resilience Fund",
    recent_feed: [
      {
        id: "sur-101",
        type: "text",
        user_location: "Varachha Ward 4",
        transcript: "Overflowing storm drain smelling of textile chemical dyes into open lane.",
        category: "Environment",
        timestamp: "3 hours ago",
      },
    ],
  },
  Kochi: {
    city_id: "IND-KL-01",
    city_name: "Kochi",
    state: "Kerala",
    tier: 2,
    location: { lat: 9.9312, lng: 76.2673 },
    risk_score: "7.3 / 10 (Moderate Hotspot)",
    priorityLevel: "Medium",
    demographics: {
      population: 677000,
      density_sq_km: 7100,
      infrastructure_index: "76/100",
    },
    complaints_summary: {
      total_received: 980,
      top_category: "Backwater Canal Desiltation & Water Metro Jetty Links",
      primary_languages: ["Malayalam", "English"],
    },
    gemini_ai_recommendation:
      "Perandoor canal silted up causing water stagnation in Kadavanthra. Dredging and reinforced embankment walls required.",
    contech_estimates: {
      suggested_structure: "Canal Sheet Piling & Tidal Flap Valve Chambers",
      estimated_concrete_m3: 490,
      estimated_steel_tons: 42,
      projected_cost_inr: "₹ 3.40 Crores",
    },
    funding_scheme: "Kochi Integrated Water Transport Project (CSML)",
    recent_feed: [
      {
        id: "koc-101",
        type: "voice",
        user_location: "Edappally Ward 33",
        transcript: "Water stagnation in canal is causing severe mosquito breeding and foul smell for residents.",
        category: "Sanitation",
        timestamp: "1.5 hours ago",
      },
    ],
  },

  // === TIER 3 CITIES ===
  Sagar: {
    city_id: "IND-MP-02",
    city_name: "Sagar",
    state: "Madhya Pradesh",
    tier: 3,
    location: { lat: 23.8388, lng: 78.7378 },
    risk_score: "7.4 / 10 (High Priority)",
    priorityLevel: "Medium",
    demographics: {
      population: 370000,
      density_sq_km: 3200,
      infrastructure_index: "54/100",
    },
    complaints_summary: {
      total_received: 680,
      top_category: "Water Supply & Filtration",
      primary_languages: ["Bundeli", "Hindi"],
    },
    gemini_ai_recommendation:
      "Water contamination reports spiked across 3 adjacent wards. Urgent requirement for a clean water treatment pump upgrade.",
    contech_estimates: {
      suggested_structure: "Submersible Pump Station & Filtration Unit",
      estimated_concrete_m3: 180,
      estimated_steel_tons: 14,
      projected_cost_inr: "₹ 85 Lakhs",
    },
    funding_scheme: "Smart Cities Mission",
    recent_feed: [
      {
        id: "feed-201",
        type: "voice",
        user_location: "Civil Lines, Sagar",
        transcript: "Drinking water supply running muddy for past 3 days in Ward 8.",
        category: "Water Supply",
        timestamp: "1 hour ago",
      },
    ],
  },
  Bhopal: {
    city_id: "IND-MP-03",
    city_name: "Bhopal",
    state: "Madhya Pradesh",
    tier: 3,
    location: { lat: 23.2599, lng: 77.4126 },
    risk_score: "6.1 / 10 (Moderate Hotspot)",
    priorityLevel: "Low",
    demographics: {
      population: 1800000,
      density_sq_km: 6300,
      infrastructure_index: "71/100",
    },
    complaints_summary: {
      total_received: 910,
      top_category: "Street Lighting & Power Grid",
      primary_languages: ["Hindi", "Urdu", "English"],
    },
    gemini_ai_recommendation:
      "Frequent street light outages near MP Nagar lake corridor causing safety concerns. Grid line maintenance needed.",
    contech_estimates: {
      suggested_structure: "Solar LED Grid & Smart Pole Array",
      estimated_concrete_m3: 65,
      estimated_steel_tons: 8,
      projected_cost_inr: "₹ 42 Lakhs",
    },
    funding_scheme: "State Infrastructure Fund",
    recent_feed: [
      {
        id: "feed-301",
        type: "text",
        user_location: "MP Nagar Zone II",
        transcript: "Entire street light line off along the lake view corridor.",
        category: "Power Grid",
        timestamp: "2 hours ago",
      },
    ],
  },
  Varanasi: {
    city_id: "IND-UP-02",
    city_name: "Varanasi",
    state: "Uttar Pradesh",
    tier: 3,
    location: { lat: 25.3176, lng: 82.9739 },
    risk_score: "8.6 / 10 (High Priority)",
    priorityLevel: "High",
    demographics: {
      population: 1200000,
      density_sq_km: 15400,
      infrastructure_index: "59/100",
    },
    complaints_summary: {
      total_received: 1780,
      top_category: "Ghat Sewage Diversion & Heritage Alley Paving",
      primary_languages: ["Bhojpuri", "Hindi"],
    },
    gemini_ai_recommendation:
      "Assi Ghat feeder nullah overflowing into river steps during peak pilgrim load. Direct interceptor line needed.",
    contech_estimates: {
      suggested_structure: "Deep Sewage Interceptor Line & Odor Neutralization Unit",
      estimated_concrete_m3: 480,
      estimated_steel_tons: 38,
      projected_cost_inr: "₹ 3.10 Crores",
    },
    funding_scheme: "Namami Gange Mission",
    recent_feed: [
      {
        id: "vns-101",
        type: "voice",
        user_location: "Assi Ghat Area",
        transcript: "Drainage backflowing near temple entrance. Pilgrims forced to step in dirty water.",
        category: "Sanitation",
        timestamp: "18 mins ago",
      },
    ],
  },
  Jabalpur: {
    city_id: "IND-MP-04",
    city_name: "Jabalpur",
    state: "Madhya Pradesh",
    tier: 3,
    location: { lat: 23.1815, lng: 79.9864 },
    risk_score: "7.0 / 10 (Moderate Hotspot)",
    priorityLevel: "Medium",
    demographics: {
      population: 1260000,
      density_sq_km: 4800,
      infrastructure_index: "61/100",
    },
    complaints_summary: {
      total_received: 840,
      top_category: "Ghamapur Drainage Outfall & Water Pipeline Leaks",
      primary_languages: ["Hindi", "Bundeli"],
    },
    gemini_ai_recommendation:
      "Water pressure variations causing pipeline ruptures across Ghamapur sector. Install electronic pressure-relief valves.",
    contech_estimates: {
      suggested_structure: "Precast Valve Chamber & Water Booster Sump",
      estimated_concrete_m3: 140,
      estimated_steel_tons: 12,
      projected_cost_inr: "₹ 68 Lakhs",
    },
    funding_scheme: "Madhya Pradesh Urban Development Co.",
    recent_feed: [
      {
        id: "jbp-101",
        type: "image",
        user_location: "Wright Town Ward 16",
        transcript: "Main road excavated 3 weeks ago for pipe repair, still unpaved with exposed mud.",
        category: "Roads",
        timestamp: "45 mins ago",
      },
    ],
  },
  Guwahati: {
    city_id: "IND-AS-01",
    city_name: "Guwahati",
    state: "Assam",
    tier: 3,
    location: { lat: 26.1445, lng: 91.7362 },
    risk_score: "8.5 / 10 (Critical Hotspot)",
    priorityLevel: "High",
    demographics: {
      population: 960000,
      density_sq_km: 4400,
      infrastructure_index: "58/100",
    },
    complaints_summary: {
      total_received: 1290,
      top_category: "Bharalu River Urban Flash Floods & Hill Siltation",
      primary_languages: ["Assamese", "Bengali", "Hindi", "English"],
    },
    gemini_ai_recommendation:
      "Bharalu river bed heavily silted, reducing discharge capacity by 65%. Urgent desiltation weir & flood walls required.",
    contech_estimates: {
      suggested_structure: "RCC River Embankment & Mechanical Silt Removal Gate",
      estimated_concrete_m3: 720,
      estimated_steel_tons: 64,
      projected_cost_inr: "₹ 4.80 Crores",
    },
    funding_scheme: "North East Special Infrastructure Development (NESIDS)",
    recent_feed: [
      {
        id: "gwt-101",
        type: "voice",
        user_location: "Rukminigaon, GS Road",
        transcript: "Water level rose 3 feet inside residential compounds within 20 minutes of rain.",
        category: "Flood Relief",
        timestamp: "12 mins ago",
      },
    ],
  },
  Solapur: {
    city_id: "IND-MH-03",
    city_name: "Solapur",
    state: "Maharashtra",
    tier: 3,
    location: { lat: 17.6599, lng: 75.9064 },
    risk_score: "6.8 / 10 (Moderate Hotspot)",
    priorityLevel: "Low",
    demographics: {
      population: 950000,
      density_sq_km: 5300,
      infrastructure_index: "60/100",
    },
    complaints_summary: {
      total_received: 720,
      top_category: "Drinking Water Frequency (Alternate Day Shortage)",
      primary_languages: ["Marathi", "Kannada", "Hindi"],
    },
    gemini_ai_recommendation:
      "Pipeline transmission loss of 32% from Ujani dam line. Smart ultrasonic acoustic flow sensors needed.",
    contech_estimates: {
      suggested_structure: "Intermediate Balancing Reservoir & Pumping House",
      estimated_concrete_m3: 390,
      estimated_steel_tons: 30,
      projected_cost_inr: "₹ 2.15 Crores",
    },
    funding_scheme: "Maharashtra Suvarna Jayanti Nagarotthan",
    recent_feed: [
      {
        id: "sol-101",
        type: "text",
        user_location: "MIDC Sector 2",
        transcript: "Water supplied once every 3 days. Factory workers and families suffering.",
        category: "Water Supply",
        timestamp: "2 hours ago",
      },
    ],
  },
  Tirunelveli: {
    city_id: "IND-TN-02",
    city_name: "Tirunelveli",
    state: "Tamil Nadu",
    tier: 3,
    location: { lat: 8.7139, lng: 77.7567 },
    risk_score: "6.5 / 10 (Moderate Hotspot)",
    priorityLevel: "Low",
    demographics: {
      population: 473000,
      density_sq_km: 4400,
      infrastructure_index: "69/100",
    },
    complaints_summary: {
      total_received: 510,
      top_category: "Thamirabarani River Bank Solid Waste Management",
      primary_languages: ["Tamil", "English"],
    },
    gemini_ai_recommendation:
      "Plastic waste washing into Thamirabarani perennial river. Deploy floating trash barriers and bio-methanation unit.",
    contech_estimates: {
      suggested_structure: "Floating Trash Boom & Decentralized Bio-Waste Digester",
      estimated_concrete_m3: 110,
      estimated_steel_tons: 9,
      projected_cost_inr: "₹ 52 Lakhs",
    },
    funding_scheme: "Tamil Nadu Sustainable Urban Development Project",
    recent_feed: [
      {
        id: "tnv-101",
        type: "image",
        user_location: "Vannarpettai Ward 11",
        transcript: "Dumping of construction debris right along river promenade walkway.",
        category: "Waste Management",
        timestamp: "4 hours ago",
      },
    ],
  },
  Ujjain: {
    city_id: "IND-MP-05",
    city_name: "Ujjain",
    state: "Madhya Pradesh",
    tier: 3,
    location: { lat: 23.1765, lng: 75.7885 },
    risk_score: "7.7 / 10 (High Priority)",
    priorityLevel: "Medium",
    demographics: {
      population: 515000,
      density_sq_km: 5600,
      infrastructure_index: "66/100",
    },
    complaints_summary: {
      total_received: 940,
      top_category: "Shipra River Flow & Mahakal Corridor Crowd Transit",
      primary_languages: ["Hindi", "Malvi"],
    },
    gemini_ai_recommendation:
      "Pilgrim surge causing bottleneck on Kshipra river bridge approach. Modular pedestrian skywalk with solar roofing recommended.",
    contech_estimates: {
      suggested_structure: "Pedestrian Steel Composite Footbridge & Evacuation Ramp",
      estimated_concrete_m3: 260,
      estimated_steel_tons: 45,
      projected_cost_inr: "₹ 2.80 Crores",
    },
    funding_scheme: "Simhastha Kumbh Special Infrastructure Corpus",
    recent_feed: [
      {
        id: "ujn-101",
        type: "voice",
        user_location: "Ram Ghat Area",
        transcript: "Huge crowd jam on narrow ghat bridge during morning aarti. No dedicated exit ramp.",
        category: "Crowd Safety",
        timestamp: "55 mins ago",
      },
    ],
  },

  // === RURAL AREAS & VILLAGES ===
  "Gram Panchayat Dharampuri": {
    city_id: "VILL-MP-01",
    city_name: "Dharampuri Village",
    state: "Madhya Pradesh",
    tier: 3,
    location: { lat: 22.1481, lng: 75.3475 },
    risk_score: "8.5 / 10 (High Priority)",
    priorityLevel: "High",
    demographics: {
      population: 4500,
      density_sq_km: 120,
      infrastructure_index: "38/100",
      is_rural: true,
      village_category: 'B',
    },
    complaints_summary: {
      total_received: 840,
      top_category: "Irrigation Canal Blockage & Agri-Supply Chain",
      primary_languages: ["Hindi", "Malvi"],
    },
    gemini_ai_recommendation:
      "Critical silt accumulation in canal distributaries. Recommend solar-powered micro-irrigation cluster and community grain storage silo.",
    contech_estimates: {
      suggested_structure: "Micro-Irrigation Sluice & 500MT Pre-Engineered Storage Silo",
      estimated_concrete_m3: 310,
      estimated_steel_tons: 65,
      projected_cost_inr: "₹ 1.20 Crores",
    },
    funding_scheme: "PM-KUSUM & NABARD Rural Infrastructure Development Fund",
    recent_feed: [
      {
        id: "v-101",
        type: "voice",
        user_location: "Ward 3, Near Primary School",
        transcript: "Primary health sub-center has no stock of anti-venom or basic first aid for two weeks.",
        regional_transcript: "प्राथमिक स्वास्थ्य केंद्र में पिछले दो हफ्तों से दवाइयां और प्राथमिक उपचार का सामान नहीं है।",
        original_audio_lang: "Hindi / Malvi",
        audio_duration_sec: 18,
        urgency_level: "Critical",
        category: "Healthcare",
        timestamp: "45 mins ago",
      },
      {
        id: "v-102",
        type: "image",
        user_location: "Canal Bridge",
        transcript: "Bridge over the canal is crumbling. Heavy tractors cannot pass.",
        category: "Infrastructure",
        timestamp: "2 hours ago",
      },
    ],
  },
  "Panchayat Ralegan Siddhi": {
    city_id: "VILL-MH-01",
    city_name: "Ralegan Siddhi",
    state: "Maharashtra",
    tier: 3,
    location: { lat: 18.9168, lng: 74.3731 },
    risk_score: "4.2 / 10 (Low Risk)",
    priorityLevel: "Low",
    demographics: {
      population: 2800,
      density_sq_km: 90,
      infrastructure_index: "82/100",
      is_rural: true,
      village_category: 'A',
    },
    complaints_summary: {
      total_received: 120,
      top_category: "Watershed Management Maintenance",
      primary_languages: ["Marathi"],
    },
    gemini_ai_recommendation:
      "Model village with robust check dams. Recommend digitalization of land records and rooftop solar grid integration for all community buildings.",
    contech_estimates: {
      suggested_structure: "Panchayat Digital Hub & Community Solar Grid",
      estimated_concrete_m3: 120,
      estimated_steel_tons: 25,
      projected_cost_inr: "₹ 0.45 Crores",
    },
    funding_scheme: "State Adarsh Gram Yojana",
    recent_feed: [
      {
        id: "v-201",
        type: "text",
        user_location: "Grama Sabha Hall",
        transcript: "Internet connectivity at the common service center is intermittent. Affecting student applications.",
        category: "Digital Connectivity",
        timestamp: "3 hours ago",
      },
    ],
  },
};

export const MOCK_GOVERNMENT_BUILDS: GovernmentBuild[] = [
  {
    id: "gb-rural-01",
    title: "Hi-Tech Rural Health Sub-Center & Wellness Lab",
    city: "Dharampuri Village",
    state: "Madhya Pradesh",
    tier: 3,
    ward: "Main Block",
    location: { lat: 22.1520, lng: 75.3520 },
    purpose: 'Hospital',
    governingBody: 'State Government (PWD)',
    contractorAgency: "State PWD District Division",
    status: 'Under Construction',
    totalCostINR: "₹ 1.45 Crores",
    costCrores: 1.45,
    timeline: "14 Months",
    completionYear: "2026",
    areaOccupied: "0.8 Acres",
    description: "Modern healthcare facility equipped with digital tele-medicine center, solar-powered refrigeration for vaccines, and emergency trauma stabilize unit.",
    citizenBeneficiaries: "6,500+ Villagers",
    citizenRating: 4.8,
    satisfactionPercent: 94,
  },
  {
    id: "gb-01",
    title: "Mahatma Jyotirao Phule Model High School & STEM Wing",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Ward 28, Scheme 78",
    location: { lat: 22.7533, lng: 75.8937 },
    purpose: "School",
    governingBody: "Municipal Corporation (Local)",
    status: "Completed",
    totalCostINR: "₹ 12.40 Crores",
    costCrores: 12.4,
    timeline: "18 Months (Started Mar 2024)",
    completionYear: "August 2025",
    areaOccupied: "42,000 sq.ft (3.2 Acres)",
    description: "Multi-storey solar-powered government school with 24 modern digital classrooms, high-spec robotics & science labs, rainwater harvesting, and mid-day meal clean kitchen.",
    citizenBeneficiaries: "1,450 students enrolled annually from underserved colonies.",
    citizenRating: 4.8,
    satisfactionPercent: 94,
    contractorAgency: "MP PWD Class-A Infrastructure Division",
    aiMapPrompt: 'Plot a marker at "Mahatma Jyotirao Phule Model High School, Scheme 78, Indore, MP". Label it: "Phule STEM Wing".',
  },
  {
    id: "gb-indore-itpark3",
    title: "IT Park-3 (MPIDC Corporate High-Rise Hub)",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Khandwa Road Tech Zone",
    location: { lat: 22.6845, lng: 75.8752 },
    purpose: "Administrative Office",
    governingBody: "Smart City SPV",
    status: "Completed",
    totalCostINR: "₹ 557.00 Crores",
    costCrores: 557.0,
    timeline: "36 Months (MPIDC Flagship)",
    completionYear: "Early 2026",
    areaOccupied: "6 Acres (19-Story Tower)",
    description: "Massive ₹557 Crore state-of-the-art tech tower built by MPIDC. Features 19-story glass-facade infrastructure, advanced multi-level automated parking, and high-speed fiber data grid for global IT companies and AI research centers.",
    citizenBeneficiaries: "14,000+ tech and engineering jobs created in Central India.",
    citizenRating: 4.9,
    satisfactionPercent: 97,
    contractorAgency: "MP Industrial Development Corporation (MPIDC)",
    aiMapPrompt: 'Plot a marker at "IT Park 3, Khandwa Road, Indore, Madhya Pradesh, India". Label it: "IT Park-3 (MPIDC Corporate High-Rise Hub)". Notes: A 19-story premium state-built tech office building.',
    sourceAttribution: "MPIDC Official / MP State Infrastructure",
  },
  {
    id: "gb-indore-itpark4",
    title: "IT Park-4 Tech Complex & AI Innovation Center",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Electronics Complex, Pardesipura",
    location: { lat: 22.7485, lng: 75.8690 },
    purpose: "Administrative Office",
    governingBody: "State Urban Development",
    status: "Completed",
    totalCostINR: "₹ 85.00 Crores",
    costCrores: 85.0,
    timeline: "22 Months",
    completionYear: "2025",
    areaOccupied: "3,785 sq. meters",
    description: "Constructed by MPIDC within the Electronics Complex. Features specialized precision clean rooms, embedded hardware labs, and high-density computing workspaces for AI and electronics manufacturing firms.",
    citizenBeneficiaries: "3,500 direct technical positions for local graduates.",
    citizenRating: 4.7,
    satisfactionPercent: 92,
    contractorAgency: "MPIDC Electronics Division",
    aiMapPrompt: 'Plot a marker at "IT Park 4, Electronics Complex, Pardesipura, Indore, Madhya Pradesh, India". Label it: "IT Park-4 Tech Complex". Notes: Focuses on hardware manufacturing and AI company offices.',
    sourceAttribution: "MPIDC & Indore Smart City",
  },
  {
    id: "gb-indore-isbt",
    title: "MR-10 InterState Bus Terminus (ISBT Super Corridor)",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Scheme No. 139-169-A, MR-10 Road",
    location: { lat: 22.7660, lng: 75.8520 },
    purpose: "Transport Hub & Bridge",
    governingBody: "Smart City SPV",
    status: "Completed",
    totalCostINR: "₹ 66.80 Crores",
    costCrores: 66.8,
    timeline: "24 Months",
    completionYear: "2025-2026",
    areaOccupied: "14 Acres",
    description: "State-of-the-art multi-modal bus terminus along Super Corridor (MR-10). Integrated passenger waiting concourse, 36 bus bays, direct subway access to Indore Metro, and solar-paneled rooftop canopy.",
    citizenBeneficiaries: "45,000 inter-state passengers traveling across MP, Maharashtra, and Rajasthan daily.",
    citizenRating: 4.8,
    satisfactionPercent: 94,
    contractorAgency: "Indore Development Authority (IDA) & BRG Infra",
    aiMapPrompt: 'Plot a marker at "ISBT, Scheme No. 139, MR-10 Road, Super Corridor, Indore, Madhya Pradesh, India". Label it: "MR-10 InterState Bus Terminus". Notes: Multi-crore mega public transit hub.',
    sourceAttribution: "IDA / Indore Smart City Development Limited",
  },
  {
    id: "gb-indore-malikheda",
    title: "Malikheda Multi-Storey Vertical Industrial Park",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Devguradiya Industrial Area",
    location: { lat: 22.6820, lng: 75.9220 },
    purpose: "Administrative Office",
    governingBody: "State Government (PWD)",
    status: "Under Construction",
    totalCostINR: "₹ 48.50 Crores",
    costCrores: 48.5,
    timeline: "24 Months (Est. Completion late 2026)",
    completionYear: "Late 2026 (70% Done)",
    areaOccupied: "10 Acres",
    description: "A first-of-its-kind 10-acre multi-story vertical factory park pioneered by the MSME department. Built to provide high-rise production floors, zero-liquid discharge effluent treatment, and plug-and-play manufacturing for new startups.",
    citizenBeneficiaries: "120+ startup manufacturing units and 4,000 industrial workers.",
    citizenRating: 4.6,
    satisfactionPercent: 90,
    contractorAgency: "MP MSME Department & State Infrastructure Board",
    aiMapPrompt: 'Plot a marker at "Devguradiya Industrial Area, Indore, Madhya Pradesh, India". Label it: "Malikheda Multi-Storey Industrial Park". Notes: A 10-acre multi-floor startup factory hub built by the MSME department.',
    sourceAttribution: "MP MSME Department",
  },
  {
    id: "gb-indore-cmrise",
    title: "CM Rise Model School (Govt. HSS Maharaja Shivaji Rao)",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Indore City Central Education Zone",
    location: { lat: 22.7150, lng: 75.8600 },
    purpose: "School",
    governingBody: "State Government (PWD)",
    status: "Completed",
    totalCostINR: "₹ 23.24 Crores",
    costCrores: 23.24,
    timeline: "16 Months",
    completionYear: "2025",
    areaOccupied: "4.5 Acres",
    description: "Signature CM Rise flagship educational complex with 32 air-cooled smart digital classrooms, robotics arena, Olympic-grade sports hall, hygienic kitchen, and transport bus fleet for rural and urban underprivileged students.",
    citizenBeneficiaries: "2,200 students receiving private-school grade free education.",
    citizenRating: 4.9,
    satisfactionPercent: 98,
    contractorAgency: "MP School Education Dept & BRG Infra",
    aiMapPrompt: 'Plot a marker at "Govt. HSS Maharaja Shivaji Rao, Indore, Madhya Pradesh, India". Label it: "CM Rise Model School Maharaja Shivaji Rao". Notes: ₹23.24 Cr advanced public school infrastructure.',
    sourceAttribution: "MP Education Infrastructure Mission",
  },
  {
    id: "gb-indore-jyotiba-garden",
    title: "Jyotiba Phule Municipal Garden & Botanical Park",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Avantika Nagar / Scheme 54",
    location: { lat: 22.7510, lng: 75.8850 },
    purpose: "Public Garden & Park",
    governingBody: "Municipal Corporation (Local)",
    status: "Completed",
    totalCostINR: "₹ 3.20 Crores",
    costCrores: 3.2,
    timeline: "10 Months",
    completionYear: "2025",
    areaOccupied: "5.5 Acres",
    description: "Beloved municipal public green haven in Avantika Nagar featuring 1.2km paved jogging track, open-air fitness gym, herbal botanical plantation, solar lighting, and children's eco-playground.",
    citizenBeneficiaries: "1,800 daily morning walkers and families from surrounding residential colonies.",
    citizenRating: 4.8,
    satisfactionPercent: 95,
    contractorAgency: "Indore Municipal Corporation (IMC) Horticulture Dept",
    aiMapPrompt: 'Plot a marker at "Jyotiba Phule Garden, Avantika Nagar, Indore, Madhya Pradesh, India". Label it: "Jyotiba Phule Municipal Park". Notes: Well-known local municipal public park in Avantika Nagar.',
    sourceAttribution: "Indore Municipal Corporation",
  },
  {
    id: "gb-indore-phule-chhatrawas",
    title: "Shri Mahatma Jyotirao Phule Savitri Bai Phule Chhatrawas",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Parmanu Nagar",
    location: { lat: 22.7020, lng: 75.8450 },
    purpose: "School",
    governingBody: "Municipal Corporation (Local)",
    status: "Completed",
    totalCostINR: "₹ 4.80 Crores",
    costCrores: 4.8,
    timeline: "12 Months",
    completionYear: "2025",
    areaOccupied: "1.8 Acres (3-Storey Hostel)",
    description: "Public-assisted student hostel and youth residential facility in Parmanu Nagar. Provides safe, affordable, subsidized boarding, reading library, high-speed internet, and study halls for aspiring students and young professionals.",
    citizenBeneficiaries: "320 resident students and career aspirants every semester.",
    citizenRating: 4.7,
    satisfactionPercent: 93,
    contractorAgency: "Social Welfare & Municipal Housing Division",
    aiMapPrompt: 'Plot a marker at "Shri Mahatma Jyotirao Phule Savitri Bai Phule Chhatrawas, Parmanu Nagar, Indore, Madhya Pradesh, India". Label it: "Mahatma Jyotirao Phule Student Chhatrawas". Notes: Community educational hostel in Parmanu Nagar.',
    sourceAttribution: "Indore Social Welfare Dept",
  },
  {
    id: "gb-indore-skye",
    title: "Skye Corporate Park (Glass-Facade Tech Landmark)",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Scheme No. 78, Vijay Nagar",
    location: { lat: 22.7565, lng: 75.8940 },
    purpose: "Administrative Office",
    governingBody: "Smart City SPV",
    status: "Completed",
    totalCostINR: "₹ 180.00 Crores",
    costCrores: 180.0,
    timeline: "30 Months",
    completionYear: "2025",
    areaOccupied: "3.5 Acres",
    description: "Standing prominently in prime Vijay Nagar / MR-10 commercial zone. A high-spec architectural glass-facade private corporate complex holding premier tech consultancies, banking centers, and co-working environments.",
    citizenBeneficiaries: "6,000 corporate professionals daily.",
    citizenRating: 4.6,
    satisfactionPercent: 91,
    contractorAgency: "Skye Group & Indore Urban Planning",
    aiMapPrompt: 'Plot a marker at "Skye Corporate Park, Scheme No 78, Vijay Nagar, Indore, Madhya Pradesh, India". Label it: "Skye Corporate Park". Notes: Prime private premium commercial glass-facade tower.',
    sourceAttribution: "Indore Commercial Property Registry",
  },
  {
    id: "gb-indore-emerald",
    title: "Emerald Forum (45m IGBC Green Certified Tower)",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Square, AB Road Commercial Corridor",
    location: { lat: 22.7450, lng: 75.8920 },
    purpose: "Administrative Office",
    governingBody: "State Urban Development",
    status: "Completed",
    totalCostINR: "₹ 140.00 Crores",
    costCrores: 140.0,
    timeline: "28 Months",
    completionYear: "2025",
    areaOccupied: "2.8 Acres",
    description: "A premium 45-metre tall commercial corporate and retail tower engineered to IGBC Gold green building standards. Features European-inspired facade, energy-efficient double glazing, and rainwater recycling.",
    citizenBeneficiaries: "Over 4,500 office workers and premium retail shoppers daily.",
    citizenRating: 4.7,
    satisfactionPercent: 93,
    contractorAgency: "Emerald Developers & Green Building Council",
    aiMapPrompt: 'Plot a marker at "Emerald Forum, AB Road Square, Indore, Madhya Pradesh, India". Label it: "Emerald Forum (45m Green Tower)". Notes: IGBC green building certified corporate and retail tower.',
    sourceAttribution: "IGBC & AB Road Commercial Registry",
  },
  {
    id: "gb-02",
    title: "Atal Bihari Vajpayee Multi-Sport Complex & Athletic Ground",
    city: "Bhopal",
    state: "Madhya Pradesh",
    tier: 3,
    ward: "Ward 45, Shahpura Sector B",
    location: { lat: 23.1950, lng: 77.4260 },
    purpose: "Sports Ground / Stadium",
    governingBody: "State Government (PWD)",
    status: "Completed",
    totalCostINR: "₹ 28.50 Crores",
    costCrores: 28.5,
    timeline: "24 Months",
    completionYear: "December 2025",
    areaOccupied: "12.5 Acres",
    description: "400m synthetic athletic track, FIFA-standard grass football turf, 4 indoor badminton wooden courts, and floodlit community cricket pitch free for local youth academies.",
    citizenBeneficiaries: "Over 3,000 sports enthusiasts & local youth daily.",
    citizenRating: 4.7,
    satisfactionPercent: 91,
    contractorAgency: "Sports Authority & MP Housing Infrastructure Board",
  },
  {
    id: "gb-03",
    title: "Parijat Urban Biodiversity Park & Stormwater Retention Lake",
    city: "Pune",
    state: "Maharashtra",
    tier: 2,
    ward: "Ward 14, Pashan Hillside",
    location: { lat: 18.5362, lng: 73.7928 },
    purpose: "Public Garden & Park",
    governingBody: "Municipal Corporation (Local)",
    status: "Completed",
    totalCostINR: "₹ 8.75 Crores",
    costCrores: 8.75,
    timeline: "14 Months",
    completionYear: "January 2026",
    areaOccupied: "18 Acres (incl. 4-acre lake)",
    description: "Revived degraded quarry into a natural ecological sponge park with 5,000 indigenous trees, 2.5km paved walking track, butterfly sanctuary, and children's sensory playground.",
    citizenBeneficiaries: "2,200 daily morning walkers and families.",
    citizenRating: 4.9,
    satisfactionPercent: 96,
    contractorAgency: "PMC Garden & Environment Department",
  },
  {
    id: "gb-04",
    title: "Dr. B.R. Ambedkar 150-Bed Government Maternity & Pediatric Hospital",
    city: "Varanasi",
    state: "Uttar Pradesh",
    tier: 3,
    ward: "Ward 31, Shivpur Bypass",
    location: { lat: 25.3582, lng: 82.9644 },
    purpose: "Hospital",
    governingBody: "State Government (PWD)",
    status: "Commissioned",
    totalCostINR: "₹ 44.80 Crores",
    costCrores: 44.8,
    timeline: "30 Months",
    completionYear: "February 2026",
    areaOccupied: "65,000 sq.ft (4.5 Acres)",
    description: "Equipped with 20 NICU beds, 4 modular operation theatres, free dialysis wing, 24x7 emergency trauma triage, and subsidized generic medicine pharmacy.",
    citizenBeneficiaries: "Catering to 450 outpatients and 30 emergency admissions daily.",
    citizenRating: 4.6,
    satisfactionPercent: 89,
    contractorAgency: "UP State Construction & Infrastructure Dev. Corp (UPPCL)",
  },
  {
    id: "gb-05",
    title: "Eastern Corridor Automated Elevated Metro Interchange & Bus Terminal",
    city: "Bengaluru",
    state: "Karnataka",
    tier: 1,
    ward: "Ward 85, KR Puram Junction",
    location: { lat: 13.0038, lng: 77.6961 },
    purpose: "Transport Hub & Bridge",
    governingBody: "State Urban Development",
    status: "Completed",
    totalCostINR: "₹ 165.00 Crores",
    costCrores: 165.0,
    timeline: "36 Months",
    completionYear: "November 2025",
    areaOccupied: "8.2 Acres built footprint",
    description: "Integrated multi-modal skywalk bridge linking Suburban Rail, Namma Metro Purple Line, and 12-bay electric feeder bus terminal with park-and-ride facility.",
    citizenBeneficiaries: "68,000 daily commuters saving 35 mins transfer time.",
    citizenRating: 4.5,
    satisfactionPercent: 88,
    contractorAgency: "BMRCL & Karnataka Infrastructure Urban Transport",
  },
  {
    id: "gb-06",
    title: "Bhatinda-Ward 6 Advanced Tertiary Sewage Treatment & Sludge Biogas Plant",
    city: "Sagar",
    state: "Madhya Pradesh",
    tier: 3,
    ward: "Ward 6, Lakha Banjara Catchment",
    location: { lat: 23.8240, lng: 78.7490 },
    purpose: "Drainage & Water Plant",
    governingBody: "Smart City SPV",
    status: "Under Construction",
    totalCostINR: "₹ 16.20 Crores",
    costCrores: 16.2,
    timeline: "20 Months (Est. Finish Oct 2026)",
    completionYear: "October 2026 (75% Done)",
    areaOccupied: "5 Acres",
    description: "15 MLD modern SBR technology wastewater recycling plant preventing untreated city sewage from polluting Sagar Lake. Features 250kW green electricity generator.",
    citizenBeneficiaries: "Protects water table for 180,000 surrounding residents.",
    citizenRating: 4.3,
    satisfactionPercent: 85,
    contractorAgency: "Sagar Smart City Development Limited",
  },
  {
    id: "gb-07",
    title: "Kurla West Subterranean Stormwater Surge Reservoir & Micro-Tunnel",
    city: "Mumbai",
    state: "Maharashtra",
    tier: 1,
    ward: "Ward L, Kurla West",
    location: { lat: 19.0680, lng: 72.8820 },
    purpose: "Drainage & Water Plant",
    governingBody: "Municipal Corporation (Local)",
    status: "Under Construction",
    totalCostINR: "₹ 82.50 Crores",
    costCrores: 82.5,
    timeline: "28 Months (Est. Completion Nov 2026)",
    completionYear: "November 2026 (60% Done)",
    areaOccupied: "Underground 3-acre basin (35M Litre capacity)",
    description: "Deep underground holding tank engineered beneath playground surface to trap flash flood water during high tide, pumped out once tide recedes.",
    citizenBeneficiaries: "Protects 350,000 residents from annual monsoon inundation.",
    citizenRating: 4.7,
    satisfactionPercent: 93,
    contractorAgency: "MCGM Storm Water Drains Department",
  },
  {
    id: "gb-08",
    title: "Assam Hills Eco-Preserve Community Sports Arena & Public Ground",
    city: "Guwahati",
    state: "Assam",
    tier: 3,
    ward: "Ward 22, Jalukbari Hillside",
    location: { lat: 26.1380, lng: 91.6670 },
    purpose: "Sports Ground / Stadium",
    governingBody: "State Government (PWD)",
    status: "Completed",
    totalCostINR: "₹ 14.60 Crores",
    costCrores: 14.6,
    timeline: "16 Months",
    completionYear: "July 2025",
    areaOccupied: "9.5 Acres",
    description: "Natural amphitheatre style football and archery ground with floodlights, rainwater swales, and outdoor gym for university students and indigenous youth clubs.",
    citizenBeneficiaries: "1,800 youth players and college students weekly.",
    citizenRating: 4.8,
    satisfactionPercent: 95,
    contractorAgency: "Assam PWD (Building) Guwahati Division",
  },
];

export const MOCK_CIVIC_PROPOSALS: CivicProposal[] = [
  {
    id: 'prop-v-01',
    title: "Gram Panchayat Cold Storage & Solar Dryer Hub",
    proposedBy: "Citizen Initiative",
    departmentOrAuthor: "Dharampuri Farmers Collective",
    city: "Dharampuri Village",
    state: "Madhya Pradesh",
    tier: 3,
    ward: "Block 2",
    locationCoords: { lat: 22.1500, lng: 75.3500 },
    purpose: 'Administrative Office',
    costEstimateINR: "₹ 85 Lakhs",
    costCrores: 0.85,
    timelineEstimated: "6 Months",
    areaRequired: "0.5 Acres",
    description: "Multi-commodity solar drying yard and a 50MT mini cold storage unit to reduce post-harvest losses for local farmers.",
    justification: "Current losses exceed 30% due to lack of immediate storage. Will benefit 400+ small-scale farmers.",
    status: 'Open for Voting',
    votesApprove: 412,
    votesReject: 12,
    citizenFeedback: [
      { id: 'f-v-01', author: 'Rajesh Kumar', vote: 'approve', comment: 'Much needed. Last year my tomatoes rotted because I couldn\'t sell them in time.', time: '1 day ago', upvotes: 24 }
    ],
    environmentalImpact: 'Positive Eco-Buffer',
    createdDate: "2026-08-20",
  },
  {
    id: "cp-gov-01",
    title: "₹72 Cr 6-Storey Luxury Administrative Secretariat & VIP Guest Towers",
    proposedBy: "Government Department",
    departmentOrAuthor: "State Urban Administrative Services",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Ward 18, Race Course Road",
    locationCoords: { lat: 22.7240, lng: 75.8790 },
    purpose: "Administrative Office",
    costEstimateINR: "₹ 72.00 Crores",
    costCrores: 72.0,
    timelineEstimated: "3.5 Years",
    areaRequired: "4.5 Acres (requires clearing 140 mature neem & banyan trees)",
    description: "Proposed luxury administrative office tower with 18 executive suites, marble foyer, 400-car underground VIP parking, and exclusive council meeting chambers.",
    justification: "To consolidate various divisional commissioner sub-offices into a single signature landmark.",
    status: "Open for Voting",
    votesApprove: 312,
    votesReject: 2480, // Heavy public rejection!
    userVoted: null,
    environmentalImpact: "Requires Tree Relocation",
    createdDate: "Aug 20, 2026",
    citizenFeedback: [
      {
        id: "cf-1",
        author: "Devendra Verma (Ward 18 Resident)",
        vote: "reject",
        comment: "REJECT THIS! Spending ₹72 Crores of taxpayer money on air-conditioned VIP suites while Ward 12 flood culverts are overflowing with sewage is an absolute disgrace.",
        time: "2 hours ago",
        upvotes: 342,
      },
      {
        id: "cf-2",
        author: "Pooja Sharma (Architecture Student)",
        vote: "reject",
        comment: "Cutting down 140 old trees in the greenest part of the city for parking spots is criminal. Convert that space into a botanical garden instead!",
        time: "5 hours ago",
        upvotes: 215,
      },
      {
        id: "cf-3",
        author: "R.K. Saxena",
        vote: "approve",
        comment: "Consolidating scattered departments might save administrative commute time.",
        time: "1 day ago",
        upvotes: 18,
      },
    ],
  },
  {
    id: "cp-gov-02",
    title: "₹38 Cr Smart Community General Hospital & 24x7 Trauma Care Centre",
    proposedBy: "Government Department",
    departmentOrAuthor: "District Health Mission & PWD",
    city: "Sagar",
    state: "Madhya Pradesh",
    tier: 3,
    ward: "Ward 12, Rahatgarh Road",
    locationCoords: { lat: 23.8450, lng: 78.7200 },
    purpose: "Hospital",
    costEstimateINR: "₹ 38.50 Crores",
    costCrores: 38.5,
    timelineEstimated: "2 Years",
    areaRequired: "6.2 Acres (Vacant unutilized government land)",
    description: "120-bed multi-specialty community hospital with mother & child health block, oxygen generation plant, digital X-ray, dialysis unit, and free ambulance triage.",
    justification: "Current district hospital is overcrowded by 300%; patients traveling 180km to Bhopal for critical trauma and dialysis.",
    status: "Open for Voting",
    votesApprove: 3890,
    votesReject: 120, // Overwhelming citizen approval!
    userVoted: null,
    environmentalImpact: "Positive Eco-Buffer",
    createdDate: "Aug 15, 2026",
    citizenFeedback: [
      {
        id: "cf-4",
        author: "Dr. Alok Mishra (Resident Physician)",
        vote: "approve",
        comment: "100% NEEDED! Our current ICU is running at 180% capacity. This will save hundreds of lives in rural Bundelkhand every month.",
        time: "1 hour ago",
        upvotes: 512,
      },
      {
        id: "cf-5",
        author: "Sunita Yadav (Social Worker)",
        vote: "approve",
        comment: "Mothers currently have to share beds in the old civil hospital. Build this immediately!",
        time: "3 hours ago",
        upvotes: 298,
      },
    ],
  },
  {
    id: "cp-gov-03",
    title: "₹45 Cr District Olympic Sports Stadium & Public Football/Cricket Ground",
    proposedBy: "Government Department",
    departmentOrAuthor: "Department of Youth & Sports Welfare",
    city: "Varanasi",
    state: "Uttar Pradesh",
    tier: 3,
    ward: "Ward 42, Sarnath Peripheral Green Zone",
    locationCoords: { lat: 25.3710, lng: 83.0230 },
    purpose: "Sports Ground / Stadium",
    costEstimateINR: "₹ 45.00 Crores",
    costCrores: 45.0,
    timelineEstimated: "2.5 Years",
    areaRequired: "16 Acres",
    description: "Multi-purpose sports stadium with 8-lane Olympic synthetic running track, grass football field, 5,000 spectator gallery, martial arts dojo, and public community jogging path.",
    justification: "Eastern UP has zero modern public synthetic athletic tracks; athletes forced to train on roadside mud tracks.",
    status: "Open for Voting",
    votesApprove: 4210,
    votesReject: 290,
    userVoted: null,
    environmentalImpact: "Moderate",
    createdDate: "Aug 18, 2026",
    citizenFeedback: [
      {
        id: "cf-6",
        author: "Virendra Singh (State Sprinter)",
        vote: "approve",
        comment: "We have to travel 300km to Lucknow just to practice on synthetic rubber tracks. This stadium will produce national champions.",
        time: "4 hours ago",
        upvotes: 430,
      },
      {
        id: "cf-7",
        author: "Mahesh Chandra",
        vote: "reject",
        comment: "Ensure the surrounding access road is widened first, otherwise traffic jams on Sarnath road will be intolerable.",
        time: "6 hours ago",
        upvotes: 84,
      },
    ],
  },
  {
    id: "cp-cit-01",
    title: "Citizen Demand: Ward 9 Public Children's Park, Senior Walking Track & Open Gym",
    proposedBy: "Citizen Initiative",
    departmentOrAuthor: "Citizen Committee of Vijay Nagar & Ward 9 Welfare Association",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Ward 9, Near Sector C Playground Plot",
    locationCoords: { lat: 22.7480, lng: 75.8910 },
    purpose: "Public Garden",
    costEstimateINR: "₹ 1.85 Crores",
    costCrores: 1.85,
    timelineEstimated: "8 Months",
    areaRequired: "2.5 Acres of encroached municipal plot",
    description: "Conversion of unmaintained dump plot into lush green neighborhood park with herbal garden, acupressure walking track, safe rubber-matted swings, and solar lights.",
    justification: "Over 6,000 families in 500m radius have zero open green space; children currently forced to play on busy traffic streets.",
    status: "Open for Voting",
    votesApprove: 2910,
    votesReject: 45,
    userVoted: null,
    environmentalImpact: "Positive Eco-Buffer",
    createdDate: "Aug 22, 2026",
    citizenFeedback: [
      {
        id: "cf-8",
        author: "Meenakshi Joshi (Grandmother & Resident)",
        vote: "approve",
        comment: "Every senior citizen in our colony signs this! We need a safe place to walk without speeding motorbikes.",
        time: "30 mins ago",
        upvotes: 185,
      },
    ],
  },
  {
    id: "cp-cit-02",
    title: "Citizen Demand: Dr. Kalam Model Higher Secondary Public School & Library",
    proposedBy: "Citizen Initiative",
    departmentOrAuthor: "Ghamapur Ward Residents & Teachers Forum",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    tier: 3,
    ward: "Ward 18, Ghamapur Slum Perimeter",
    locationCoords: { lat: 23.1780, lng: 79.9650 },
    purpose: "School",
    costEstimateINR: "₹ 6.40 Crores",
    costCrores: 6.4,
    timelineEstimated: "14 Months",
    areaRequired: "1.8 Acres (Vacant Municipal School land)",
    description: "State-of-the-art government English & Hindi medium school with free digital computer lab, library with competitive exam books, and clean sanitation blocks.",
    justification: "Over 3,200 children from low-income families drop out after class 8 because nearest high school is 7 km across busy railway lines.",
    status: "Open for Voting",
    votesApprove: 3410,
    votesReject: 22,
    userVoted: null,
    environmentalImpact: "Minimal",
    createdDate: "Aug 25, 2026",
    citizenFeedback: [
      {
        id: "cf-9",
        author: "Kailash Tiwari (Retired Principal)",
        vote: "approve",
        comment: "Education is our greatest infrastructure. Build this school before sanctioning any more VIP flyovers!",
        time: "15 mins ago",
        upvotes: 490,
      },
    ],
  },
  {
    id: "cp-gov-04",
    title: "₹110 Cr Commercial Shopping Complex & Private Multiplex Hub",
    proposedBy: "Government Department",
    departmentOrAuthor: "State Urban Development Corporation",
    city: "Pune",
    state: "Maharashtra",
    tier: 2,
    ward: "Ward 21, Aundh DP Road",
    locationCoords: { lat: 18.5580, lng: 73.8050 },
    purpose: "Administrative Office",
    costEstimateINR: "₹ 110.00 Crores",
    costCrores: 110.0,
    timelineEstimated: "4 Years",
    areaRequired: "8 Acres",
    description: "Commercial multi-level retail mall with cinema multiplex, private commercial lease spaces, and multi-tier basement parking.",
    justification: "To generate commercial lease revenue for the municipal corporation.",
    status: "Open for Voting",
    votesApprove: 280,
    votesReject: 3820, // Overwhelmingly rejected as useless luxury build!
    userVoted: null,
    environmentalImpact: "Moderate",
    createdDate: "Aug 10, 2026",
    citizenFeedback: [
      {
        id: "cf-10",
        author: "Ananya Deshpande (Urban Planner)",
        vote: "reject",
        comment: "REJECT THIS! Aundh already has 4 private shopping malls with 40% empty retail space. The city needs public healthcare clinics and water drainage, NOT another shopping mall built with public tax revenue!",
        time: "2 hours ago",
        upvotes: 620,
      },
      {
        id: "cf-11",
        author: "Siddharth Kulkarni",
        vote: "reject",
        comment: "This is purely useless infrastructure meant to benefit private retail contractors. Reject completely!",
        time: "4 hours ago",
        upvotes: 380,
      },
    ],
  },
  {
    id: "cp-future-indore-aerocity",
    title: "Indore Aerocity Mega Hub (Hospitality & Multi-Modal Logistics)",
    proposedBy: "Government Department",
    departmentOrAuthor: "Indore Development Authority (IDA) & MP Civil Aviation",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "500m from Devi Ahilyabai Holkar Airport",
    locationCoords: { lat: 22.7230, lng: 75.8010 },
    purpose: "Administrative Office",
    costEstimateINR: "₹ 550.00 Crores",
    costCrores: 550.0,
    timelineEstimated: "3.5 Years",
    areaRequired: "11 Hectares (Prime Aerotropolis Land)",
    description: "A ₹500–600 Crore smart commercial ecosystem planned on 11 hectares of land just 500 meters from Devi Ahilyabai Holkar International Airport. Features premium hotels, corporate office complexes, and high-end residential setups seamlessly connected to the Indore-Pithampur Economic Corridor.",
    justification: "To establish Indore as an international business aviation gateway and logistics transit hub for central India.",
    status: "Open for Voting",
    votesApprove: 3820,
    votesReject: 410,
    userVoted: null,
    environmentalImpact: "Moderate",
    createdDate: "Aug 26, 2026",
    isFutureMegaProject: true,
    aiMapPrompt: 'Plot a marker 500 meters from "Devi Ahilyabai Holkar International Airport, Indore, Madhya Pradesh, India". Label it: "Proposed Indore Aerocity Mega Hub". Notes: Upcoming 11-hectare hospitality and commercial ecosystem.',
    citizenFeedback: [
      {
        id: "cf-indore-aero-1",
        author: "Nitesh Singhal (Logistics Entrepreneur)",
        vote: "approve",
        comment: "Essential for Indore's export sector! Having luxury hotels and conference halls right by the runway will attract global IT summits.",
        time: "25 mins ago",
        upvotes: 142,
      },
      {
        id: "cf-indore-aero-2",
        author: "Radhika Malviya (Environmental Advocate)",
        vote: "reject",
        comment: "Ensure buffer green zoning is legally protected before cutting open more farmland near Depalpur road.",
        time: "1 hour ago",
        upvotes: 68,
      },
    ],
  },
  {
    id: "cp-future-indore-twintowers",
    title: "Proposed IDA Twin Towers (87.60m Tallest Financial Hub)",
    proposedBy: "Government Department",
    departmentOrAuthor: "Indore Development Authority (IDA)",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Super Corridor Financial Zone",
    locationCoords: { lat: 22.7710, lng: 75.8450 },
    purpose: "Administrative Office",
    costEstimateINR: "₹ 850.00 Crores",
    costCrores: 850.0,
    timelineEstimated: "4 Years",
    areaRequired: "7.5 Acres",
    description: "Set to become Indore's tallest structure at 87.60 metres high. The IDA is planning iconic twin towers featuring 3 basements, a 4-floor shopping mall, international convention centre, and 5-star business hotel on the Super Corridor.",
    justification: "To create an iconic central financial hub rivaling GIFT City and BKC.",
    status: "Open for Voting",
    votesApprove: 2190,
    votesReject: 3410, // Hotly debated! Many citizens demand healthcare instead
    userVoted: null,
    environmentalImpact: "Moderate",
    createdDate: "Aug 24, 2026",
    isFutureMegaProject: true,
    aiMapPrompt: 'Plot a marker on "Super Corridor, Indore, Madhya Pradesh, India". Label it: "Proposed IDA Twin Towers (87.60m Tallest Hub)". Notes: Future financial district with 5-star hotel and convention center.',
    citizenFeedback: [
      {
        id: "cf-indore-tt-1",
        author: "Manish Chawla (Taxpayer & Resident)",
        vote: "reject",
        comment: "₹850 Crores on 5-star hotels and luxury malls?! Put this budget into finishing the underground drainage in the outer ring wards first!",
        time: "15 mins ago",
        upvotes: 492,
      },
      {
        id: "cf-indore-tt-2",
        author: "Deepak Agrawal (Realtor)",
        vote: "approve",
        comment: "This will put MP on the global architectural map. High-density vertical growth is better than urban sprawl.",
        time: "45 mins ago",
        upvotes: 89,
      },
    ],
  },
  {
    id: "cp-future-indore-station",
    title: "Indore Junction 7-Story Airport-Style Redevelopment Complex",
    proposedBy: "Government Department",
    departmentOrAuthor: "Ministry of Railways & RLDA",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Chhoti Gwaltoli, Central Indore",
    locationCoords: { lat: 22.7177, lng: 75.8682 },
    purpose: "Transport Hub & Bridge",
    costEstimateINR: "₹ 412.00 Crores",
    costCrores: 412.0,
    timelineEstimated: "3 Years (Target: 2027)",
    areaRequired: "4.56 Lakh sq. ft Built Footprint",
    description: "Comprehensive ₹412 Crore airport-grade modernization of Indore Junction. Features a 7-story main terminal building, rooftop solar panels, multi-tier passenger parking, 26 high-speed escalators & elevators, and direct segregated arrival/departure concourses.",
    justification: "Passenger load has grown by 240%; historic terminal is severely congested during festival rush.",
    status: "Open for Voting",
    votesApprove: 4950,
    votesReject: 110,
    userVoted: null,
    environmentalImpact: "Minimal",
    createdDate: "Aug 22, 2026",
    isFutureMegaProject: true,
    aiMapPrompt: 'Plot a marker at "Indore Junction Railway Station, Chhoti Gwaltoli, Indore, Madhya Pradesh, India". Label it: "Indore Station 7-Story Redevelopment Complex". Notes: Airport-like modern transit building ongoing through 2027.',
    citizenFeedback: [
      {
        id: "cf-indore-st-1",
        author: "Anil Sethi (Daily Passenger)",
        vote: "approve",
        comment: "Long overdue! The current foot overbridge is dangerously bottlenecked. 26 lifts and segregated arrivals will be life-saving for elders.",
        time: "10 mins ago",
        upvotes: 388,
      },
    ],
  },
  {
    id: "cp-future-indore-metro",
    title: "Indore Metro Yellow Line Corridor & Indore-Ujjain 47km Link",
    proposedBy: "Government Department",
    departmentOrAuthor: "MP Metro Rail Corporation Limited (MPMRCL)",
    city: "Indore",
    state: "Madhya Pradesh",
    tier: 2,
    ward: "Super Corridor - MR-10 - Ujjain Transit Alignment",
    locationCoords: { lat: 22.7690, lng: 75.8480 },
    purpose: "Transport Hub & Bridge",
    costEstimateINR: "₹ 2,800.00 Crores",
    costCrores: 2800.0,
    timelineEstimated: "4 Years",
    areaRequired: "31.5 km Ring Route + 47 km Inter-City Link",
    description: "Following the commissioning of Priority Corridor-2 (Super Corridor-3 to Malviya Nagar Chauraha), construction is accelerating to close the full 31.5 km Yellow Line loop, alongside the DPR for the 47 km high-speed Indore-Ujjain regional rapid transit metro line.",
    justification: "Will eliminate 120,000 car/bus daily trips, drastically slashing carbon emissions between the twin spiritual and economic capitals.",
    status: "Open for Voting",
    votesApprove: 5610,
    votesReject: 195,
    userVoted: null,
    environmentalImpact: "Minimal",
    createdDate: "Aug 20, 2026",
    isFutureMegaProject: true,
    aiMapPrompt: 'Draw a route starting from "Super Corridor-3 Metro Station" passing through "MR-10" to "Malviya Nagar Chauraha, Indore, MP, India". Label it: "Indore Metro Yellow Line Corridor". Notes: 31.5 km Yellow Line ring and 47 km Ujjain rapid link.',
    citizenFeedback: [
      {
        id: "cf-indore-metro-1",
        author: "Dr. Vikram Patidar (Commuter)",
        vote: "approve",
        comment: "Connecting Indore directly to Mahakal Ujjain via high-speed metro will be transformative for pilgrims, students, and daily office commuters.",
        time: "35 mins ago",
        upvotes: 520,
      },
    ],
  },
];

// Comprehensive AI Map Prompts Dataset specifically curated for Indore
export const INDORE_AI_MAP_PROMPTS: AIMapPromptItem[] = [
  {
    id: "aimp-itpark3",
    title: "IT Park-3 (MPIDC Corporate High-Rise Hub)",
    category: "Government & Public Infra",
    locationName: "Khandwa Road, Indore",
    coords: { lat: 22.6845, lng: 75.8752 },
    budgetOrCost: "₹ 557.00 Crores",
    areaOrSize: "6 Acres (19-Story Building)",
    purpose: "Offices for IT companies, AI services, and corporate high-rises",
    builtBy: "MPIDC (MP Industrial Development Corporation)",
    status: "Completed",
    keyHighlight: "19-story high-rise building with massive multi-level parking and global IT leases",
    notes: "A massive ₹557 Crore project built on 6 acres. Designed to hold major IT companies with high-capacity digital fiber.",
    exactPrompt: 'Plot a marker at "IT Park 3, Khandwa Road, Indore, Madhya Pradesh, India". Label it: "IT Park-3 (MPIDC Corporate High-Rise Hub)". Notes: A 19-story premium state-built tech office building.',
  },
  {
    id: "aimp-itpark4",
    title: "IT Park-4 Tech Complex",
    category: "Government & Public Infra",
    locationName: "Electronics Complex, Pardesipura, Indore",
    coords: { lat: 22.7485, lng: 75.8690 },
    budgetOrCost: "₹ 85.00 Crores",
    areaOrSize: "3,785 sq. meters",
    purpose: "Hardware manufacturing, AI startups & high-density computing",
    builtBy: "MPIDC",
    status: "Completed",
    keyHighlight: "Specialized clean rooms and embedded labs inside Electronics Complex",
    notes: "Built by MPIDC inside the Electronics Complex spanning 3,785 square meters.",
    exactPrompt: 'Plot a marker at "IT Park 4, Electronics Complex, Pardesipura, Indore, Madhya Pradesh, India". Label it: "IT Park-4 Tech Complex". Notes: Focuses on hardware manufacturing and AI company offices.',
  },
  {
    id: "aimp-isbt",
    title: "MR-10 InterState Bus Terminus (ISBT)",
    category: "Government & Public Infra",
    locationName: "Scheme No. 139-169-A, MR-10 Road, Super Corridor, Indore",
    coords: { lat: 22.7660, lng: 75.8520 },
    budgetOrCost: "₹ 66.80 Crores",
    areaOrSize: "14 Acres",
    purpose: "Multi-modal mega public transit terminus with 36 bays",
    builtBy: "Indore Development Authority (IDA) / Smart City",
    status: "Completed",
    keyHighlight: "Multi-crore public transit hub connecting directly to the Indore Metro",
    notes: "Constructed at Scheme No. 139-169-A along the Super Corridor costing ₹66.80 Crores.",
    exactPrompt: 'Plot a marker at "ISBT, Scheme No. 139, MR-10 Road, Super Corridor, Indore, Madhya Pradesh, India". Label it: "MR-10 InterState Bus Terminus". Notes: Multi-crore mega public transit hub.',
  },
  {
    id: "aimp-malikheda",
    title: "Malikheda Vertical Industrial Park",
    category: "Government & Public Infra",
    locationName: "Devguradiya Industrial Area, Indore",
    coords: { lat: 22.6820, lng: 75.9220 },
    budgetOrCost: "₹ 48.50 Crores",
    areaOrSize: "10 Acres Multi-Floor Layout",
    purpose: "High-rise vertical workspaces and manufacturing for startups",
    builtBy: "MP MSME Department",
    status: "Under Construction",
    keyHighlight: "10-acre multi-story industrial building hub for urban production efficiency",
    notes: "Unique multi-story industrial building hub built to provide vertical workspaces for startups.",
    exactPrompt: 'Plot a marker at "Devguradiya Industrial Area, Indore, Madhya Pradesh, India". Label it: "Malikheda Multi-Storey Industrial Park". Notes: A 10-acre multi-floor startup factory hub built by the MSME department.',
  },
  {
    id: "aimp-cmrise",
    title: "CM Rise Model School (Maharaja Shivaji Rao)",
    category: "Government & Public Infra",
    locationName: "Govt. HSS Maharaja Shivaji Rao, Indore",
    coords: { lat: 22.7150, lng: 75.8600 },
    budgetOrCost: "₹ 23.24 Crores",
    areaOrSize: "4.5 Acres",
    purpose: "Advanced STEM digital classrooms and free public secondary schooling",
    builtBy: "MP School Education Department & State PWD",
    status: "Completed",
    keyHighlight: "Flagship public education complex with smart robotics and sports facilities",
    notes: "State-of-the-art public school infrastructure with digital laboratories and transport network.",
    exactPrompt: 'Plot a marker at "Govt. HSS Maharaja Shivaji Rao, Indore, Madhya Pradesh, India". Label it: "CM Rise Model School Maharaja Shivaji Rao". Notes: ₹23.24 Cr advanced public school infrastructure.',
  },
  {
    id: "aimp-jyotiba-garden",
    title: "Jyotiba Phule Municipal Garden & Park",
    category: "Government & Public Infra",
    locationName: "Avantika Nagar / Scheme 54, Indore",
    coords: { lat: 22.7510, lng: 75.8850 },
    budgetOrCost: "₹ 3.20 Crores",
    areaOrSize: "5.5 Acres",
    purpose: "Public park, walking tracks, open gym, and family botanical zone",
    builtBy: "Indore Municipal Corporation (IMC)",
    status: "Completed",
    keyHighlight: "Lush green recreational open space named in honor of Mahatma Jyotirao Phule",
    notes: "Well-known local municipal public park situated in Avantika Nagar with open jogging loops.",
    exactPrompt: 'Plot a marker at "Jyotiba Phule Garden, Avantika Nagar, Indore, Madhya Pradesh, India". Label it: "Jyotiba Phule Municipal Park". Notes: Well-known local municipal public park in Avantika Nagar.',
  },
  {
    id: "aimp-phule-chhatrawas",
    title: "Shri Mahatma Jyotirao Phule Savitri Bai Phule Chhatrawas",
    category: "Government & Public Infra",
    locationName: "Parmanu Nagar, Indore",
    coords: { lat: 22.7020, lng: 75.8450 },
    budgetOrCost: "₹ 4.80 Crores",
    areaOrSize: "1.8 Acres (3-Storey Hostel)",
    purpose: "Affordable student hostel & accommodation for young professionals",
    builtBy: "Municipal & Social Welfare Corporation",
    status: "Completed",
    keyHighlight: "Subsidized boarding, digital library, and study halls for aspiring students",
    notes: "Local community hostel located in Parmanu Nagar offering affordable accommodation.",
    exactPrompt: 'Plot a marker at "Shri Mahatma Jyotirao Phule Savitri Bai Phule Chhatrawas, Parmanu Nagar, Indore, Madhya Pradesh, India". Label it: "Mahatma Jyotirao Phule Student Chhatrawas". Notes: Community educational hostel in Parmanu Nagar.',
  },
  {
    id: "aimp-phule-circle",
    title: "Jyotiba Phule Circle (Musakhedi Chauraha)",
    category: "Government & Public Infra",
    locationName: "Musakhedi Square, Ring Road, Indore",
    coords: { lat: 22.7050, lng: 75.9050 },
    budgetOrCost: "₹ 1.80 Crores",
    areaOrSize: "Key Ring Road Intersection",
    purpose: "Civic landmark, rotary traffic island & memorial square",
    builtBy: "Indore Municipal Corporation (IMC)",
    status: "Completed",
    keyHighlight: "Prominent civic landmark honoring social reformer Mahatma Jyotirao Phule",
    notes: "Prominent public landmark square located in the Musakhedi area connecting Ring Road.",
    exactPrompt: 'Plot a marker at "Musakhedi Square, Indore, Madhya Pradesh, India". Label it: "Jyotiba Phule Circle". Notes: Prominent public square on Ring Road named in honor of Mahatma Jyotirao Phule.',
  },
  {
    id: "aimp-skye",
    title: "Skye Corporate Park",
    category: "Private & Corporate Landmark",
    locationName: "Scheme No 78, Vijay Nagar / MR-10, Indore",
    coords: { lat: 22.7565, lng: 75.8940 },
    budgetOrCost: "₹ 180.00 Crores",
    areaOrSize: "3.5 Acres",
    purpose: "Premium commercial business & tech office complex",
    builtBy: "Skye Group",
    status: "Completed",
    keyHighlight: "Premier glass-facade tower in Vijay Nagar business district",
    notes: "Standing highly rated glass-facade private business complexes situated around prime Vijay Nagar.",
    exactPrompt: 'Plot a marker at "Skye Corporate Park, Scheme No 78, Vijay Nagar, Indore, Madhya Pradesh, India". Label it: "Skye Corporate Park". Notes: Prime private premium commercial glass-facade tower.',
  },
  {
    id: "aimp-emerald",
    title: "Emerald Forum (45m Green Tower)",
    category: "Private & Corporate Landmark",
    locationName: "AB Road Square, Indore",
    coords: { lat: 22.7450, lng: 75.8920 },
    budgetOrCost: "₹ 140.00 Crores",
    areaOrSize: "45m Height / 2.8 Acres",
    purpose: "Commercial corporate & retail tower with IGBC Gold certification",
    builtBy: "Emerald Developers",
    status: "Completed",
    keyHighlight: "IGBC certified green building with European-inspired classical architecture",
    notes: "45-metre tall commercial corporate and retail tower certified green by IGBC.",
    exactPrompt: 'Plot a marker at "Emerald Forum, AB Road Square, Indore, Madhya Pradesh, India". Label it: "Emerald Forum (45m Green Tower)". Notes: IGBC green building certified corporate and retail tower.',
  },
  {
    id: "aimp-metrocorp",
    title: "Metro Corporates Commercial Hub",
    category: "Private & Corporate Landmark",
    locationName: "Super Corridor, Indore",
    coords: { lat: 22.7750, lng: 75.8400 },
    budgetOrCost: "₹ 125.00 Crores",
    areaOrSize: "4 Acres Built Footprint",
    purpose: "Multi-tenant tech company offices and luxury corporate spaces",
    builtBy: "Metro Corporates Consortium",
    status: "Completed",
    keyHighlight: "Direct visibility along the Super Corridor Metro alignment",
    notes: "Prime commercial office infrastructure housing tech startups and financial institutions.",
    exactPrompt: 'Plot a marker at "Super Corridor, Indore, Madhya Pradesh, India". Label it: "Metro Corporates Commercial Hub". Notes: Premier private commercial building on the Super Corridor.',
  },
  {
    id: "aimp-sarthak",
    title: "Sarthak Square Commercial Landmark",
    category: "Private & Corporate Landmark",
    locationName: "MR-5 / Chota Bangarda Road, Indore",
    coords: { lat: 22.7380, lng: 75.8290 },
    budgetOrCost: "₹ 45.00 Crores",
    areaOrSize: "1.5 Acres",
    purpose: "Corporate offices, bank branches & retail commercial stores",
    builtBy: "Sarthak Group",
    status: "Completed",
    keyHighlight: "Rapidly developing business node connecting airport bypass corridor",
    notes: "Commercial retail and office landmark serving Western Indore neighborhoods.",
    exactPrompt: 'Plot a marker at "Chota Bangarda Road, Indore, Madhya Pradesh, India". Label it: "Sarthak Square Commercial Landmark". Notes: Key commercial hub in Western Indore.',
  },
  {
    id: "aimp-aerocity",
    title: "Proposed Indore Aerocity Mega Hub",
    category: "Mega Future Construction",
    locationName: "500m from Devi Ahilyabai Holkar Airport, Indore",
    coords: { lat: 22.7230, lng: 75.8010 },
    budgetOrCost: "₹ 550.00 Crores (Est. ₹500–600 Cr)",
    areaOrSize: "11 Hectares",
    purpose: "Hospitality, premium hotels, office complexes & air logistics",
    builtBy: "Indore Development Authority (IDA)",
    status: "Proposed / Voting",
    keyHighlight: "World-class aerotropolis connected to Indore-Pithampur Economic Corridor",
    notes: "A ₹500–600 Crore smart commercial ecosystem planned on 11 hectares just 500 meters from the airport.",
    exactPrompt: 'Plot a marker 500 meters from "Devi Ahilyabai Holkar International Airport, Indore, Madhya Pradesh, India". Label it: "Proposed Indore Aerocity Mega Hub". Notes: Upcoming 11-hectare hospitality and commercial ecosystem.',
  },
  {
    id: "aimp-twintowers",
    title: "Proposed IDA Twin Towers (87.60m Tallest Financial Hub)",
    category: "Mega Future Construction",
    locationName: "Super Corridor, Indore",
    coords: { lat: 22.7710, lng: 75.8450 },
    budgetOrCost: "₹ 850.00 Crores",
    areaOrSize: "87.60m Height / 7.5 Acres",
    purpose: "Financial district, 4-floor mall, convention centre & 5-star hotel",
    builtBy: "Indore Development Authority (IDA)",
    status: "Proposed / Voting",
    keyHighlight: "Set to become Central India's tallest architectural structure (87.60m)",
    notes: "Iconic twin towers featuring 3 basements, shopping mall, convention centre, and 5-star hotel.",
    exactPrompt: 'Plot a marker on "Super Corridor, Indore, Madhya Pradesh, India". Label it: "Proposed IDA Twin Towers (87.60m Tallest Hub)". Notes: Future financial district with 5-star hotel and convention center.',
  },
  {
    id: "aimp-station",
    title: "Indore Station 7-Story Airport-Style Redevelopment Complex",
    category: "Mega Future Construction",
    locationName: "Indore Junction Railway Station, Chhoti Gwaltoli, Indore",
    coords: { lat: 22.7177, lng: 75.8682 },
    budgetOrCost: "₹ 412.00 Crores",
    areaOrSize: "4.56 Lakh sq. ft Built Footprint",
    purpose: "7-story main terminal, multi-level parking & 26 passenger lifts",
    builtBy: "Rail Land Development Authority (RLDA) / Indian Railways",
    status: "Proposed / Voting",
    keyHighlight: "Airport-like passenger separation and solar-powered concourse (target 2027)",
    notes: "A multi-phase ₹400+ Crore airport-style upgrade with 26 passenger lifts and multi-level parking.",
    exactPrompt: 'Plot a marker at "Indore Junction Railway Station, Chhoti Gwaltoli, Indore, Madhya Pradesh, India". Label it: "Indore Station 7-Story Redevelopment Complex". Notes: Airport-like modern transit building ongoing through 2027.',
  },
  {
    id: "aimp-metro",
    title: "Indore Metro Yellow Line & 47km Ujjain Rapid Link",
    category: "Mega Future Construction",
    locationName: "Super Corridor to MR-10 to Ujjain Corridor, Indore",
    coords: { lat: 22.7690, lng: 75.8480 },
    budgetOrCost: "₹ 2,800.00 Crores",
    areaOrSize: "31.5 km Yellow Ring + 47 km Inter-City Route",
    purpose: "Rapid mass transit network linking twin cultural and industrial cities",
    builtBy: "MPMRCL (MP Metro Rail Corporation Limited)",
    status: "Proposed / Voting",
    keyHighlight: "Priority Corridor-2 operational; Yellow loop & 47km Mahakal Ujjain link progressing",
    notes: "High-speed transit connecting Super Corridor, MR-10, Malviya Nagar, and extending to Ujjain.",
    exactPrompt: 'Draw a route starting from "Super Corridor-3 Metro Station" passing through "MR-10" to "Malviya Nagar Chauraha, Indore, MP, India". Label it: "Indore Metro Yellow Line Corridor". Notes: 31.5 km Yellow Line ring and 47 km Ujjain rapid link.',
  },
];
